[package]
name = "native_image_compress"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
anyhow = "1.0"
flutter_rust_bridge = { version = "1.82.6", features = ["zero-copy"] }
image = "0.25.1"
kamadak-exif = "0.5.5"

[profile.dev]
lto = true
panic = "abort"
opt-level = "z"
strip = "debuginfo"

[profile.release]
lto = true
panic = "abort"
opt-level = "z"
strip = "debuginfo"
